### ISSUE TITLE
Some errors

### ISSUE THREAD

**Issue by simlan123** [trapd00r/firefox-remote#1]
Hey trapd00r I tried to use your skript on my ubuntu machine with perl 5.8.8 it threw this errors:

```
Warning: Use of "shift" without parentheses is ambiguous at ./fxr line 29.
Scalar found where operator expected at ./fxr line 29, near "// $m"
(Missing operator before  $m?)
syntax error at ./fxr line 29, near "// $m"
Execution of ./fxr aborted due to compilation errors.
```

Cant figure out the problem cause dont know perl... Problem is propablly on my site maybe wrong version of Perl or something similar?

**Comment by trapd00r** [comment]
You're right; you are using an ancient version of Perl.
You'll need at least Perl 5.10.
The reason for this is because of the 'test-if-defined' operator, '//', that was added to the Perl core with the 5.10 release.

**Comment by simlan123** [comment]
Okay thanks ;) . Should update my dev box in near future... Thanks
